# Generated by Django 5.0.6 on 2024-06-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=45)),
                ('motifs', models.CharField(choices=[('EXAMEN DE LA VUE', 'CHOIX DE LUNETTES '), ('AJUSTEMENT DE LUNETTES', 'AJUSTEMENT DE LUNETTESSUIVI\xa0ET\xa0CONTRÔLE')], default='EXAMEN DE LA VUE', max_length=60)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
            ],
        ),
    ]
