# Generated by Django 5.0.6 on 2024-06-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monOpticien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='motifs',
            field=models.CharField(choices=[('EV', 'EXAMEN DE LA VUE'), ('CL', 'CHOIX DE LUNETTES '), ('AL', 'AJUSTEMENT DE LUNETTES'), ('SC', 'SUIVI\xa0ET\xa0CONTRÔLE')], default='EXAMEN DE LA VUE', max_length=60),
        ),
    ]
